
/**************************************************************
 *	
 *	intromusic, 8 bit, 11025Hz,
 *	1 channel, 1457568 bytes/channel
 *	Total Size: 1 * 1457568 + 4 (header) = 1457612 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Kyle\Desktop\LAB FILES\sound lab\wav2c\intromusic.wav
 *	Time-stamp: Sun Dec 05 03:38:37 2010
 *	
 **************************************************************/

#ifndef __INTROMUSICH__
#define __INTROMUSICH__

#define INTROMUSICFREQ 11025
#define INTROMUSICLEN 1457568

extern const unsigned char intromusic[1457568];

#endif /* __INTROMUSICH__ */
