
/**************************************************************
 *	
 *	chop, 8 bit, 11025Hz,
 *	1 channel, 3744 bytes/channel
 *	Total Size: 1 * 3744 + 4 (header) = 3788 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Kyle\Desktop\LAB FILES\sound lab\wav2c\chop.wav
 *	Time-stamp: Mon Dec 06 06:30:16 2010
 *	
 **************************************************************/

#ifndef __CHOPH__
#define __CHOPH__

#define CHOPFREQ 11025
#define CHOPLEN 3744

extern const unsigned char chop[3744];

#endif /* __CHOPH__ */
