
/**************************************************************
 *	
 *	gamemusic, 8 bit, 11025Hz,
 *	1 channel, 1639296 bytes/channel
 *	Total Size: 1 * 1639296 + 4 (header) = 1639340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Kyle\Desktop\LAB FILES\sound lab\wav2c\gamemusic.wav
 *	Time-stamp: Sun Dec 05 03:36:37 2010
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 1639296

extern const unsigned char gamemusic[1639296];

#endif /* __GAMEMUSICH__ */
